version: '3'
services:

  admin-web:
    restart: always
    entrypoint: ./build.sh
    env_file: .env
    build:
      context: .
      dockerfile : dockerfiles/main/Dockerfile
    ports:
      - 5003:5003
    networks:
        default:
                ipv4_address: 172.16.238.15

networks:
  default:
    external:
        name : open-vote-api_app_net
