version: '3'
services:

  vote-admin-web:
    restart: always
    entrypoint: ./build.sh
    env_file: .env
    ports:
    - 5003:5003
    build:
      context: .
      dockerfile : dockerfiles/main/Dockerfile
    networks:
    - traefik-net
    labels:
    - "traefik.frontend.rule=Host:vote-admin.vousmeevoyez.xyz"

networks:
  traefik-net:
    external: true
